# Generated by Django 4.2.7 on 2025-10-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, help_text='Precisao da localizacao em metros', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Velocidade em km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direcao em graus', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude em metros', null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('driving', 'Dirigindo'), ('stopped', 'Parado'), ('break', 'Em Pausa')], default='online', max_length=20)),
                ('battery_level', models.IntegerField(blank=True, help_text='Nivel da bateria em %', null=True)),
                ('is_gps_enabled', models.BooleanField(default=True)),
                ('device_id', models.CharField(blank=True, help_text='ID unico do dispositivo', max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp do GPS')),
            ],
            options={
                'verbose_name': 'Localizacao do Motorista',
                'verbose_name_plural': 'Localizacoes dos Motoristas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DriverTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluida'), ('cancelled', 'Cancelada')], default='started', max_length=20)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Viagem do Motorista',
                'verbose_name_plural': 'Viagens dos Motoristas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Localizacao',
                'verbose_name_plural': 'Localizacoes',
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('completed', 'Concluida'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sessao de Teste',
                'verbose_name_plural': 'Sessoes de Teste',
            },
        ),
    ]
