# Generated by Django 4.2.7 on 2025-10-02 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testsession',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='end_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_ended', to='core.driverlocation'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='start_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_started', to='core.driverlocation'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['driver', '-timestamp'], name='core_driver_driver__804e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['status', '-timestamp'], name='core_driver_status_6d77e7_idx'),
        ),
    ]
