# Generated by Django 4.2.7 on 2025-10-21 16:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(help_text='CPF do motorista', max_length=14, unique=True)),
                ('name', models.CharField(help_text='Nome completo do motorista', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Telefone do motorista', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Motorista ativo')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='location',
        ),
        migrations.AlterModelOptions(
            name='driverlocation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Localização do Motorista', 'verbose_name_plural': 'Localizações dos Motoristas'},
        ),
        migrations.RemoveIndex(
            model_name='driverlocation',
            name='core_driver_status_6d77e7_idx',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='is_gps_enabled',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='start_location',
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='Precisão da localização em metros', null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='battery_level',
            field=models.IntegerField(blank=True, help_text='Nível da bateria em %', null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp do GPS'),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='started', max_length=20),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.driver'),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.driver'),
        ),
    ]
