# Generated by Django 4.2.7 on 2025-10-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_driver_remove_location_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Posição atual durante a viagem', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Posição atual durante a viagem', max_digits=10, null=True),
        ),
    ]
