# Generated by Django 4.2.7 on 2025-10-27 21:28

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ativo_user_cpf_perfilusuario_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_drivertrip_current_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_frete', models.CharField(default='Frete', help_text='Nome/Descrição do Frete (ex: Frete Postes, Entrega Material)', max_length=255)),
                ('numero_nota_fiscal', models.CharField(blank=True, help_text='Número da Nota Fiscal (opcional)', max_length=50, null=True, unique=True)),
                ('codigo_publico', models.CharField(blank=True, help_text='Código público para acompanhamento sem login', max_length=10, unique=True)),
                ('tipo_servico', models.CharField(choices=[('TRANSPORTE', 'Transporte de Materiais'), ('MUNCK_CARGA', 'Serviço Munck - Carregamento'), ('MUNCK_DESCARGA', 'Serviço Munck - Descarregamento')], default='TRANSPORTE', help_text='Define o fluxo de trabalho do serviço', max_length=20)),
                ('origem', models.CharField(blank=True, help_text='Endereço de partida (opcional)', max_length=255, null=True)),
                ('origem_link_google', models.URLField(blank=True, help_text='Link do Google Maps para a origem', max_length=500, null=True)),
                ('destino', models.CharField(blank=True, help_text='Endereço de entrega (opcional)', max_length=255, null=True)),
                ('destino_link_google', models.URLField(blank=True, help_text='Link do Google Maps para o destino', max_length=500, null=True)),
                ('data_agendamento', models.DateField(default=django.utils.timezone.now, help_text='Data agendada para o serviço')),
                ('hora_agendamento', models.TimeField(blank=True, help_text='Hora agendada para o serviço (formato HH:MM)', null=True)),
                ('data_hora_agendamento', models.DateTimeField(blank=True, help_text='Data e hora completa do agendamento', null=True)),
                ('status_atual', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('CANCELADO', 'Cancelado'), ('AGUARDANDO_CARGA', 'Aguardando Carga'), ('EM_TRANSITO', 'Em Trânsito'), ('EM_DESCARGA_CLIENTE', 'Chegou no Destino'), ('FINALIZADO', 'Entrega Finalizada'), ('CARREGAMENTO_NAO_INICIADO', 'Carregamento não Iniciado'), ('CARREGAMENTO_INICIADO', 'Carregamento Iniciado'), ('CARREGAMENTO_CONCLUIDO', 'Carregamento Concluído'), ('DESCARREGAMENTO_NAO_INICIADO', 'Descarregamento não Iniciado'), ('DESCARREGAMENTO_INICIADO', 'Descarregamento Iniciado'), ('DESCARREGAMENTO_CONCLUIDO', 'Descarregamento Concluído')], default='NAO_INICIADO', max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro no sistema')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_chegada_cd', models.DateTimeField(blank=True, help_text='Transporte: Chegou para carregar', null=True)),
                ('data_inicio_viagem', models.DateTimeField(blank=True, help_text='Transporte: Carga concluída, viagem iniciada', null=True)),
                ('data_chegada_destino', models.DateTimeField(blank=True, help_text='Transporte: Chegou ao destino para descarregar', null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, help_text='Transporte: Entrega finalizada com sucesso', null=True)),
                ('data_inicio_operacao_munck', models.DateTimeField(blank=True, help_text='Munck: Início do carregamento/descarregamento', null=True)),
                ('data_fim_operacao_munck', models.DateTimeField(blank=True, help_text='Munck: Fim do carregamento/descarregamento', null=True)),
                ('tempo_estimado_horas', models.IntegerField(default=2, help_text='Tempo estimado em horas para conclusão da operação')),
                ('data_limite_notificacao', models.DateTimeField(blank=True, help_text='Data limite calculada para notificações', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais sobre o serviço', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(default=apps.core.models.get_default_user, on_delete=django.db.models.deletion.PROTECT, related_name='fretes', to='users.cliente')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretes_como_motorista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('NAO_INICIADO', 'Não Iniciado'), ('CANCELADO', 'Cancelado'), ('AGUARDANDO_CARGA', 'Aguardando Carga'), ('EM_TRANSITO', 'Em Trânsito'), ('EM_DESCARGA_CLIENTE', 'Chegou no Destino'), ('FINALIZADO', 'Entrega Finalizada'), ('CARREGAMENTO_NAO_INICIADO', 'Carregamento não Iniciado'), ('CARREGAMENTO_INICIADO', 'Carregamento Iniciado'), ('CARREGAMENTO_CONCLUIDO', 'Carregamento Concluído'), ('DESCARREGAMENTO_NAO_INICIADO', 'Descarregamento não Iniciado'), ('DESCARREGAMENTO_INICIADO', 'Descarregamento Iniciado'), ('DESCARREGAMENTO_CONCLUIDO', 'Descarregamento Concluído')], max_length=30, null=True)),
                ('status_novo', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('CANCELADO', 'Cancelado'), ('AGUARDANDO_CARGA', 'Aguardando Carga'), ('EM_TRANSITO', 'Em Trânsito'), ('EM_DESCARGA_CLIENTE', 'Chegou no Destino'), ('FINALIZADO', 'Entrega Finalizada'), ('CARREGAMENTO_NAO_INICIADO', 'Carregamento não Iniciado'), ('CARREGAMENTO_INICIADO', 'Carregamento Iniciado'), ('CARREGAMENTO_CONCLUIDO', 'Carregamento Concluído'), ('DESCARREGAMENTO_NAO_INICIADO', 'Descarregamento não Iniciado'), ('DESCARREGAMENTO_INICIADO', 'Descarregamento Iniciado'), ('DESCARREGAMENTO_CONCLUIDO', 'Descarregamento Concluído')], max_length=30)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='core.frete')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Histórico de Status',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador da rota', max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data/hora de início da rota', null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Data/hora de conclusão da rota', null=True)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', help_text='Status atual da rota', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a rota', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('motorista', models.ForeignKey(blank=True, help_text='Motorista responsável pela rota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas_atribuidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PontoLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_localizacao', to='core.frete')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Poste Circular-12/1000', max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(default='un.', help_text='Ex: un., metros, kg', max_length=50)),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='core.frete')),
            ],
        ),
        migrations.CreateModel(
            name='FotoFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_fretes/')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.frete')),
            ],
        ),
        migrations.CreateModel(
            name='FreteRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(help_text='Ordem de execução do frete na rota')),
                ('status_rota', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', help_text='Status do frete dentro da rota', max_length=20)),
                ('data_inicio_execucao', models.DateTimeField(blank=True, help_text='Data/hora de início da execução', null=True)),
                ('data_conclusao_execucao', models.DateTimeField(blank=True, help_text='Data/hora de conclusão da execução', null=True)),
                ('frete', models.ForeignKey(help_text='Frete incluído na rota', on_delete=django.db.models.deletion.CASCADE, to='core.frete')),
                ('rota', models.ForeignKey(help_text='Rota à qual o frete pertence', on_delete=django.db.models.deletion.CASCADE, related_name='fretes_rota', to='core.rota')),
            ],
            options={
                'verbose_name': 'Frete da Rota',
                'verbose_name_plural': 'Fretes da Rota',
                'ordering': ['ordem'],
                'unique_together': {('rota', 'frete')},
            },
        ),
    ]
